# Carbohydrate Calculator : Selenium Test Framework
# Configuration file
app.url=https://www.calculator.net/carbohydrate-calculator.html

#For extent report header
env=production
# Options: chrome | chrome-headless | firefox | firefox-headless | edge
browser=safari

# Explicit wait (seconds) used by WaitUtils
explicit.wait.sec=15

# Page load timeout (seconds) :set on the WebDriver
page.load.timeout.sec=30